---
id: Promise和async
title: Promise和async
author: 李川
author_title: 随便写写
author_url: https://github.com/newlichuan
author_image_url: img/logo.jpg
---

#### 异步解决方案....

<!--truncate-->

## 什么是异步

首先,JS 引擎是单线程的,意味着同一时间只能做一件事,  
但是呢,浏览器提供了许多供我们使用的接口,这些接口的作用  
一般都是需要花一定时间去做一件事的,例如 ajax,settimeout,node 中的读写文件  
显然此时 JS 引擎是不可能干等着呢 所以  
 异步可以算是浏览器提供的一种能力,既一些任务可以以后台的方式运行  
例如

```js
setTimeOut(() => console.log(123), 1000);
```

## 管理异步

既然有此类任务,我们自然需要在任务完成时去做一些事情  
来管理这些异步任务,目前有三种解决方案

### 1. 回调函数

回调就是,讲一个函数作为参数,传递给某个任务,等待任务完成时  
会去调用这个函数,在调用链短的时候还是挺方便的

```js
ajax.get("/test/", function (res) {
  console.log(res);
});
```

但是一旦调用链过长,则需要在这个会调里再次填写回调  
此时著名的回调地狱就出现了

```js
ajax.get("/test/", function (res) {
  console.log(res);
  ajax.get("/test1/", function (res) {
    console.log(res2);
    ajax.get("/test2/", function (res) {
      console.log(res3);
      ajax.get("/test3/", function (res) {
        console.log(res);
      });
    });
  });
});
```

此时无论在代码可读性还是错误处理都十分棘手  
这是出现了 es6 新增的 Promise 来解决这个问题

### 2. Promise

Promise 是 JS 内置的一个构造函数,代表承诺的意思  
既然回调有状态,那么就用一个对象来当这个状态的占位符  
 语法

```js
const p = new Promise(function (reslove, reject) {
  ajax(...res(data));
});
```

new 调用 接收一个函数参数,这个函数会立即执行  
这个函数会接收两个参数,一个代表成功 reslove,  
一个代表失败的 reject
返回值是一个 Promise 对象,默认状态是 pedding
代表未决议 当异步任务内完成后会调用 reslove 函数  
此时状态变为成功,**状态只能改变一次,后续会忽略**

```js
p.then(e => console.log(e));
p.then(e => console.log(e));
p.then(e => console.log(e));
```

返回的对象有一个 then 方法,接收一个回调函数,代表成功状态时执行的函数
一个Promise可以多次调用then,会按传入顺序执行(一般不这么做)  
会把 res()的返回值传入这个回调,这个 then 方法也会返回一个 Promise  
供链式调用,这个 Promise 会在 **then 里的回调执行后变为成功状态**,  
并且**已此回调的返回值传递到下一个 then**  
如果**这个回到返回一个新的 Promise 则会以这个新的 promise 为准**;
**可以在任何时间段绑定then,哪怕已经是成功状态下绑定**
例子一:返回值为新的 promise 时

```js
const js = new Promsie(res => {
  res();
});
const a = js.then(e => new Promise(() => {}));
console.log(a); // peddning
```

例子二:返回值非 promise 时

```js
const js = new Promsie(res => {
  res();
});
const a = js.then(e => 123);
console.log(a); // resolve  value:123
```

**并且执行完默认还是返回成功的 Promise**

#### 错误处理

既然有成功状态 自然有失败的状态 失败状态是以 reject 来确认的  
使用.catch 的回调来执行,并传入错误对象,同样可以链式调用  
并且可以捕获前面所有的错误

```js
const Pro = new Promise((res, rej) => {
  rej();
});
Pro.then(() => {})
  .then(() => {})
  .catch(e => {
    console.log(e);
  });
```

此时前面的 then 都不会执行,直接执行 catch 的回调

#### finally

无论成功与否都会执行的回调,不接受参数

#### Promise.all([])

处理并行问题,例如发送 5 个请求,需要等 5 个请求都完成后执行某个函数
有一个失败后就返回失败,其余不再关心

#### Promise.race()

竞赛,以第一个改变的状态为结果,其余的作废

#### Promise.resolve()

返回一个成功的 Promise,参数为返回值

#### Promise.reject()

返回失败 Promise 参数为错误对象

其实 promise 也是传递的回调函数,只不过他解决了嵌套的问题  
变成了链式调用 写法上看着更清晰

### 3. async

es6 新增的生成器函数,给与了函数暂停执行的能力  
配合 Promise 形成了更好的管理异步的方式,所以官方结合这两者出了 async  
就是像写同步代码一样写异步代码;  
语法用下

```js
async function func() {
  const a = await new Promise(res => {
    setTimeOut(() => res(123), 1000);
  });
  console.log(a);
}
```

函数前加一个 async 关键字 此关键字表示此函数会返回一个 Promise  
函数内部可以使用 await(只能用在 async 函数内) 关键字  
表示等待后面的异步操作完成后继续返回内部执行  
并且将返回的值传递回来,供下面继续使用,如果 await 后面不是一个 Promise  
会将这个值直接传递过来(本质是将这个值套一个成功的 promise)

```js
async function func() {
  const a = await 123;
  console.log(a);
}
name();
console.log(1); //1 123
```

**await 下面的代码块,可以看做是传入 then 的回调函数,也是属于微任务**  
这点不要被误导,因为看起来像是同步代码  
并且这个 async 函数的返回值是 return 的值,如果返回了新的 promise  
则会使用这个新的 promise,这点跟上面是一致的;

```js
async function func() {
  const a = await 123;
  console.log(a);
  return a;
}
async function func1() {
  const b = await func();
  console.log(b); // 123
}
func1();
```

#### 错误处理

由于 async 没有.catch 方法,所以需要用 try..catch 来解决错误问题  
应为切换到错误状态时,会抛出一个错误

```js
async function func() {
  try {
    await new Promise((res, rej) => {
      rej();
    });
  } catch (e) {
    console.log(e);
  }
}
func();
```

## 总结

普通的回调 属于嵌套调用  
Promise 属于链式调用  
async await 属于像同步代码一样管理异步
